version: '3'

services:
  api:
    container_name: newsletter-builder-api
    build: 
      context: ./api
      dockerfile: Dockerfile.alpine
    restart: always
    ports:
     - "8000:8000"
    volumes:
     - ./api:/api
    environment:
      TINIFY_API_KEY: "${TINIFY_API_KEY}"

  web:
    container_name: newsletter-builder-web
    build:
      context: ./web
    restart: always
    ports:
     - "80:80"
    depends_on:
      - api
