apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apiName" . }}-tinify-api-key
  labels:
    {{- include "releaseLabels" . | indent 4 }}
type: Opaque
data:
  tinify-api-key: {{ .Values.api.tinifyApiKey | b64enc | quote }}
