envName: prod
hostname: nb.k8s.sandbox.ggops.com

api:
  image:
    repository: mechtron/newsletter-builder-api
    tag: k8s-helm
  serviceType: NodePort
  tinifyApiKey: s3cr3t # use --set to override this in production

web:
  image:
    repository: mechtron/newsletter-builder-web
    tag: k8s-helm
  serviceType: NodePort
