FROM python:3.7-alpine3.12

# RUN apk --update add --no-cache musl-dev mysql-client
RUN apk --update add --no-cache libffi-dev gcc openssl-dev python3-dev
RUN pip3 install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

RUN mkdir /api
COPY . /api

EXPOSE 8000

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONUNBUFFERED=1

WORKDIR /api
CMD python3 app.py
