FROM ubuntu:18.04

RUN apt-get update && \
  apt-get install -y python3-pip curl dnsutils && \
  # apt-get install -y libmysqlclient-dev mysql-client && \
  rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

RUN mkdir /api
COPY . /api

EXPOSE 8000

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONUNBUFFERED=1

WORKDIR /api
CMD python3 app.py
