name: Build & deploy to Amazon S3
on:
  push:
    branches:
    - master
jobs:
  build_and_deploy_job:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: "9.x"
    - run: cd web && npm install
    - run: cd web && npm run build
    - name: Sync to S3 bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: newsletter-builder
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: ./web/dist/
